name: CI
on: [push, pull_request]
jobs:
  CompileRust:
   name: Compile Rust
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2

      - name: Install Cargo
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Compile...
        working-directory: ./sensor_Interface
        run: cargo build

  Tests:
    name: Run UI tests with Cypress
    runs-on: ubuntu-latest
    needs: CompileRust
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install Packages
        working-directory: ./api
        run: npm install

      - name: Compile Typescript
        working-directory: ./static
        run: npx tsc

      - name: Start Sensor Interface
        working-directory: ./sensor_Interface
        run: cargo run -- --debug &

      - name: Start Web Server
        working-directory: ./api
        run: node src --debug &

      - name: Run Cypress
        working-directory: ./api
        run: npx cypress run

      - name: Shutdown Servers
        run: |
          curl http://localhost:3030/EXIT
          curl http://localhost:8080/EXIT

  runRustTests:
    name: Run Rust Unit Tests
    runs-on: ubuntu-latest
    needs: CompileRust
    steps:
      - uses: actions/checkout@v2

      - name: Run Unit Tests
        working-directory: ./sensor_Interface
        run: cargo test
