name: Format and Tests
on: [push, pull_request]
jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: Prettier
        run: npx prettier --write "{,!(node_modules)**}*.js"
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Mr. Code Format'
          git config --global user.email 'codeformat@connorcode.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "💎 Automated Code Formatting"
          git push origin HEAD:master

  Tests:
    name: Run UI tests with Cypress
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: cd api
      - run: npm install
      - run: node src --debug &
      - run: npx cypress run
    
